# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  
  pod 'Alamofire'
  pod 'SwifterSwift'
  
end

target 'KeyboardToolbar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyboardToolbar
  shared_pods


end

target 'Nostr Image Board' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nostr Image Board
  shared_pods


end
